class ProcessCommands:
    IS_MOVING = 'im'
    IS_ROTATING = 'ir'
    ALTITUDE_VALID = 'av'
    IS_MAGNETOMETER_CALIBRATED = 'imc'
    MAGNETIC_DISTURBANCE = 'md'

    YAW = 'y'
    PITCH = 'p'
    ROLL = 'r'
    COMPASS_HEADING = 'c'
    ZERO_YAW = 'z'

    IS_CALIBRATING = 'ca'
    IS_CONNECTED = 'co'
    BYTE_COUNT = 'bc'
    UPDATE_COUNT = 'uc'
    WORLD_LINEAR_ACCEL_X = 'wlax'
    WORLD_LINEAR_ACCEL_Y = 'wlay'
    WORLD_LINEAR_ACCEL_Z = 'wlaz'
    BAROMETRIC_PRESSUE = 'bp'
    ALTITUDE = 'a'
    FUSED_HEADING = 'fh'
    QUATERNION_W = 'qw'
    QUATERNION_X = 'qx'
    QUATERNION_Y = 'qy'
    QUATERNION_Z = 'qz'
    RESET_DISPLACEMENT = 'rd'
    VELOCITY_X = 'vx'
    VELOCITY_Y = 'vy'
    VELOCITY_Z = 'vz'
    DISPLACEMENT_X = 'dx'
    DISPLACEMENT_Y = 'dy'
    DISPLACEMENT_Z = 'dz'
    TEMP_C = 'tc'
